# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Romain Roehrig
email: romain.roehrig@meteo.fr
description: > # this means to ignore newlines until "baseurl:"
  Atmospheric Physicist, Climate modeler
baseurl: "" # the subpath of your site, e.g. /blog
url: http://romainroehrig.github.io/
github_username:  romainroehrig
orcid_username: 0000-0002-3903-3841
orcid_address: https://orcid.org/0000-0002-3903-3841
scholar_username: romain.roehrig
scholar_address: https://scholar.google.com/citations?user=hX0LUeEAAAAJ
header-img: img/home-bg.jpg

# Build settings
markdown: kramdown
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
